version: '3'
services:
  node-server:
    build: .
    container_name: indigo-node-server
    image: meanless/node-alpine
    volumes:
      - ./src:/apps/node-server/src
    ports:
      - '7000:7000'
    restart: always
    env_file:
      - ./.env
    working_dir: /apps/node-server
    command: ['npm', 'run', 'start']
