version: '3'
services:
  node-server:
    build: .
    container_name: indigo-node-server
    image: meanless/indigo-node
    volumes:
      - ./src:/apps/node-server/src
      - ./logs:/apps/node-server/logs
      - ./pm2.config.js:/apps/node-server/pm2.config.js
    ports:
      - '7000:7000'
    restart: always
    env_file:
      - ./prod.env
    working_dir: /apps/node-server
    command: ['npm', 'run', 'start']
